name: meme_cloud
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  firebase_core:
  firebase_auth:
  supabase_flutter: ^2.0.0
  get_it:
  dartz:
  flutter_dotenv: ^5.2.1
  just_audio: ^0.9.46
  audio_session: ^0.1.25
  audio_service: ^0.18.18
  audio_video_progress_bar: ^2.0.3
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env
    - assets/icons/

