// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxV84IJicQQ3GQwqxdrt8sySWZnrD3j6I',
    appId: '1:756517239189:web:c6cabefc92c66006e9de9c',
    messagingSenderId: '756517239189',
    projectId: 'meme-cloud-8a470',
    authDomain: 'meme-cloud-8a470.firebaseapp.com',
    storageBucket: 'meme-cloud-8a470.firebasestorage.app',
    measurementId: 'G-8LKP44VS1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQNnnUF8TlSHmxIK_5kIp1fTITR8LcLI',
    appId: '1:756517239189:android:ce969b94177382e8e9de9c',
    messagingSenderId: '756517239189',
    projectId: 'meme-cloud-8a470',
    storageBucket: 'meme-cloud-8a470.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqlHZLaFiei8NwG37WwMWVlAXnzup2Xik',
    appId: '1:756517239189:ios:a85b4037c4362045e9de9c',
    messagingSenderId: '756517239189',
    projectId: 'meme-cloud-8a470',
    storageBucket: 'meme-cloud-8a470.firebasestorage.app',
    iosBundleId: 'com.example.memeCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqlHZLaFiei8NwG37WwMWVlAXnzup2Xik',
    appId: '1:756517239189:ios:a85b4037c4362045e9de9c',
    messagingSenderId: '756517239189',
    projectId: 'meme-cloud-8a470',
    storageBucket: 'meme-cloud-8a470.firebasestorage.app',
    iosBundleId: 'com.example.memeCloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxV84IJicQQ3GQwqxdrt8sySWZnrD3j6I',
    appId: '1:756517239189:web:82cd4a9e596c0598e9de9c',
    messagingSenderId: '756517239189',
    projectId: 'meme-cloud-8a470',
    authDomain: 'meme-cloud-8a470.firebaseapp.com',
    storageBucket: 'meme-cloud-8a470.firebasestorage.app',
    measurementId: 'G-QF0BKLRBLN',
  );
}
